
spring:
  application:
    name: reddit-service
  datasource:
    url: jdbc:postgresql://localhost:5432/reddit
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    name: reddit
  jpa:
    hibernate:
      ddl-auto: create
      event:
        merge:
          entity:
            listener:
              enabled: true
    show-sql: true
    properties:
      hibernate:
        create_namespaces: true
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  security:
    enabled: false
  web:
    cors:
      allowed-origin=*
      allowed-headers=*
      allowed-methods=GET,POST,PUT,DELETE
  sql:
    init:
      mode: always
server:
  port: 8080

weather:
  api:
    key: 5cbe6ca8ac66447bbc9173923230806
    url: https://api.weatherapi.com/v1/current.json
    location: London

  # Specify the path of the OpenAPI documentation
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /api-docs